# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    volumes:
      - matcha_nginx_data:/data

  ui:
    stdin_open: true
    build:
      context: ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui:/app #Allows source folders to be watched

  server:
    command: ["yarn", "debug"]
    ports:
      - "127.0.0.1:9229:9229" # Allows remote debugging
    volumes:
      - ./server/src:/app/src # Allows source folders to be watched
      - ./server/config:/app/config
      - matcha_server_data:/data
    environment:
      - MATCHA_ENV=local
      - MATCHA_LOG_LEVEL=debug

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - matcha_mongodb_data:/data

  elasticsearch:
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - matcha_elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    ports:
      - "127.0.0.1:5601:5601"

  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    container_name: matcha_umami
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: replace-me-with-a-random-string
    depends_on:
      - postgres
    networks:
      - matcha_network

  postgres:
    image: postgres:12-alpine
    container_name: matcha_umami_db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - matcha_umami_data:/var/lib/postgresql/data
    depends_on:
      - server
    networks:
      - matcha_network

volumes:
  matcha_elasticsearch_data:
    driver: local
    name: matcha_elasticsearch_data
  matcha_mongodb_data:
    driver: local
    name: matcha_mongodb_data
  matcha_nginx_data:
    driver: local
    name: matcha_nginx_data
  matcha_server_data:
    driver: local
    name: matcha_server_data
  matcha_umami_data:
    driver: local
    name: matcha_umami_data
